import json
import re
from collections import defaultdict

import pandas as pd


# # Comprehensive regex for bipolar disorder self-identification
# bipolar_regex = r'\b(bipolar disorder|bipolar|manic depressive illness|bipolar I|bipolar II|cyclothymia|diagnosed with bipolar|I have bipolar|living with bipolar disorder|diagnosed with manic depression|bipolar diagnosis|I was diagnosed with bipolar|mood swings|manic episode|depressive episode|manic depression|rapid cycling|highs and lows|elevated mood|euphoric|mania|manic|hypomanic|hypomania|depressed|severe depression|feeling invincible|can\'t sleep during manic episode|racing thoughts|talking fast|reckless behavior|impulsive decisions|bipol\b|manic-depressive|I feel bipolar|I\'m bipolar|been told I\'m bipolar|I think I\'m bipolar|I\'ve been diagnosed as bipolar|people say I\'m bipolar|acting bipolar|extreme highs|extreme lows|feeling euphoric|feeling invincible|over-the-top happiness|over-the-top energy|feeling empty|feeling worthless|deep depression|suicidal thoughts during lows|feeling on top of the world|feeling down in the dumps|lithium|valproate|divalproex|lamotrigine|abilify|seroquel|quetiapine|mood stabilizer|antipsychotics for bipolar|bipolar meds|bipolar medication|been living with bipolar for years|I\'ve struggled with bipolar my whole life|my bipolar diagnosis|my manic depression diagnosis|I\'ve always been bipolar|I\'ve known I\'m bipolar|my therapist says I\'m bipolar|psychiatrist diagnosed me with bipolar|mental health issues|mental illness|I suffer from mental illness|mental health condition|struggling with mental health|my mental health|feeling mentally unstable|unbalanced mentally)\b'
#
# # Comprehensive regex for depression self-identification
# depression_regex = r'\b(major depressive disorder|clinical depression|severe depression|diagnosed with depression|I have depression|I was diagnosed with depression|living with depression|depressive disorder|depressive episode|persistent depressive disorder|dysthymia|I have MDD|MDD diagnosis|depression diagnosis|feeling sad all the time|feeling hopeless|feeling worthless|can\'t enjoy anything|loss of interest|loss of energy|fatigue|feeling empty|feeling numb|suicidal thoughts|thoughts of suicide|self-harm|self harm|can\'t get out of bed|sleeping too much|insomnia|lack of motivation|overwhelming sadness|extreme sadness|crying all the time|feeling overwhelmed|can\'t stop crying|feeling like a burden|I hate myself|feeling depressed|I\'m so depressed|I think I have depression|I feel depressed all the time|depressed af|I\'m really down|I\'m always sad|I\'ve been depressed for years|people tell me I\'m depressed|struggling with depression|dealing with depression|my depression|fighting depression|I think I\'m depressed|feeling worthless|feeling hopeless|feeling like a failure|losing hope|can\'t find joy|losing interest in life|nothing feels good anymore|I feel like giving up|I\'m in a dark place|feeling lost|feeling broken|I feel empty|emotionally drained|numb inside|no hope left|life is pointless|life feels meaningless|prozac|fluoxetine|zoloft|sertraline|lexapro|escitalopram|citalopram|celexa|paxil|paroxetine|wellbutrin|bupropion|effexor|venlafaxine|antidepressants|taking antidepressants|on depression meds|SSRI|SNRI|mood stabilizer for depression|depression medication|I\'ve been struggling with depression for years|I\'ve been living with depression|my depression diagnosis|I\'ve battled depression|I\'ve had depression my whole life|I\'ve suffered from depression|I\'ve always had depression|I\'ve known I was depressed|my therapist says I\'m depressed|my psychiatrist diagnosed me with depression|mental health issues|mental illness|struggling with mental health|I suffer from mental illness|my mental health is bad|struggling mentally|emotionally exhausted|mentally exhausted|feeling mentally drained|my mental health condition)\b'

# # Comprehensive regex for anxiety disorder self-identification
# anxiety_regex = r'\b(anxiety disorder|generalized anxiety disorder|GAD|social anxiety disorder|social phobia|panic disorder|panic attacks|chronic anxiety|diagnosed with anxiety|I have anxiety|living with anxiety disorder|diagnosed with GAD|my anxiety diagnosis|I was diagnosed with anxiety|feeling anxious|constant worry|excessive worry|panic attack|feeling nervous|overthinking|fear of the future|feeling overwhelmed|can\'t stop worrying|always anxious|heart racing|shortness of breath|sweating from anxiety|shaking from anxiety|butterflies in my stomach|dread|feeling on edge|restlessness|racing thoughts|trouble sleeping due to anxiety|insomnia from anxiety|anxious af|I\'m anxious|I feel anxious|feeling panicked|panic setting in|I think I have anxiety|people say I have anxiety|acting anxious|my anxiety is through the roof|I\'m having a panic attack|been told I\'m anxious|freaking out|I\'m freaking out|freaking anxious|feeling nervous all the time|I\'ve been told I worry too much|feeling scared|feeling tense|feeling paralyzed by fear|overwhelmed by fear|crippling anxiety|fear of social situations|can\'t relax|hypervigilance|feeling like something bad will happen|afraid of the worst|irrational fears|catastrophizing|extreme nervousness|social anxiety|fear of public speaking|fear of crowds|fear of rejection|nervous around people|avoiding people because of anxiety|job interview anxiety|test anxiety|school anxiety|fear of failure|panic in crowded places|fear of flying|anxiety in social situations|SSRIs for anxiety|benzodiazepines for anxiety|anxiety meds|taking medication for anxiety|Xanax|Ativan|Klonopin|Valium|anxiolytics|therapy for anxiety|CBT for anxiety|cognitive behavioral therapy for anxiety|meditation for anxiety|breathing exercises for anxiety|I\'ve been dealing with anxiety for years|I\'ve always had anxiety|I struggle with anxiety|my anxiety disorder|I can\'t manage my anxiety|I get anxious easily|I was diagnosed with anxiety|my therapist said I have anxiety|my psychiatrist diagnosed me with anxiety|mental health issues|mental illness|struggling with mental health|I suffer from mental illness|my mental health|anxiety about my mental health|feeling mentally unwell|struggling with anxiety)\b'

# # Comprehensive regex for ADHD self-identification
# adhd_regex = r'\b(attention[- ]deficit hyperactivity disorder|adhd|add|diagnosed with adhd|i have adhd|living with adhd|diagnosed with attention[- ]deficit disorder|adhd diagnosis|add diagnosis|inattention|impulsive|hyperactivity|distracted easily|can’t focus|trouble focusing|difficulty concentrating|easily bored|forgetful|restless|fidgety|always on the go|can\'t sit still|easily distracted|procrastination|losing things|unorganized|overwhelmed|disorganized|lack of focus|short attention span|add\b|adhd\b|hyperactive|can’t focus for long|i feel adhd|i think i have adhd|been told i have adhd|i have add|been told i have add|i feel like i have adhd|adhd-like behavior|adhd struggles|always losing things|impulsive decisions|interrupted others|speak too quickly|trouble organizing|hyperfocus|time management issues|interrupting conversations|jumping between tasks|feeling overwhelmed|can’t finish tasks|started but didn’t finish|mentally exhausted|overwhelmed by tasks|frustrated with myself|anxious because i can\'t focus|i feel scattered|i feel all over the place|can’t keep up|my mind is racing|feel out of control|brain fog|my brain won’t stop|feeling frustrated with attention|i can\'t slow down|ritalin|adderall|vyvanse|concerta|dexedrine|atomoxetine|methylphenidate|stimulants for adhd|adhd medication|adhd meds|medication for attention deficit|meds for hyperactivity|been living with adhd for years|i’ve struggled with adhd my whole life|adhd diagnosis|my attention deficit diagnosis|i have trouble focusing because of adhd|been diagnosed with adhd for as long as i can remember|i was diagnosed with adhd when i was younger|my therapist says i have adhd|psychiatrist diagnosed me with adhd|mental health struggles|struggling with mental health|mental health condition|difficulty managing mental health|issues with attention|challenges with focus and mental health)\b'

# # Comprehensive regex for PTSD and C-PTSD self-identification
# cptsd_regex = r'\b(post[- ]traumatic stress disorder|ptsd|complex ptsd|c[- ]ptsd|trauma[- ]related disorder|trauma[- ]induced stress|diagnosed with ptsd|diagnosed with c[- ]ptsd|complex post[- ]traumatic stress|I have ptsd|living with ptsd|diagnosed with post[- ]traumatic stress disorder|ptsd diagnosis|c[- ]ptsd diagnosis|flashbacks|nightmares|re[- ]experiencing trauma|hypervigilance|panic attacks|intrusive memories|avoidance behaviors|emotional numbness|feeling detached|feeling on edge|excessive alertness|difficulty sleeping due to trauma|startling easily|reliving the trauma|feeling like it\'s happening again|dissociation|emotional flashbacks|intense distress at trauma reminders|overwhelming memories of the trauma|feeling traumatized|I\'m traumatized|been told I have ptsd|I think I have ptsd|been diagnosed with ptsd|I feel like I have ptsd|I suffer from ptsd|I have trauma|acting like I have ptsd|trauma survivor|trauma-related stress|struggling with ptsd|I feel c-ptsd symptoms|survived trauma|sexual abuse survivor|domestic violence survivor|war veteran|combat trauma|rape survivor|childhood abuse|emotional abuse|physical abuse|natural disaster survivor|accident survivor|experiencing trauma|past trauma|military trauma|combat[- ]related ptsd|abuse[- ]related ptsd|victim of trauma|survivor of trauma|experiencing flashbacks from the trauma|extreme anxiety|panic attacks|constant fear|fear of something bad happening|feeling unsafe|feeling out of control|overwhelmed by fear|uncontrollable anxiety|emotional shutdown|feeling emotionally numb|emotionally overwhelmed|fear of being hurt again|trust issues after trauma|fear of trusting people|been living with ptsd|I\'ve struggled with ptsd my whole life|my ptsd diagnosis|my complex ptsd diagnosis|I think I have c[- ]ptsd|my therapist says I have ptsd|I\'ve been diagnosed with ptsd|psychiatrist diagnosed me with ptsd|I struggle with post-traumatic stress|I suffer from ptsd symptoms|I have complex trauma|I have post[- ]traumatic stress disorder|I live with c-ptsd|I have been diagnosed with trauma-related stress|ptsd symptoms control my life|antidepressants for ptsd|ssri|prozac|zoloft|therapy for ptsd|counseling for trauma|trauma therapy|trauma-focused therapy|eye movement desensitization and reprocessing|emdr|cognitive behavioral therapy|cbt|therapy for trauma-related stress|difficulty regulating emotions|feeling worthless|feeling like a failure|difficulty with relationships|avoiding intimacy|difficulty trusting others|difficulty maintaining friendships|feeling broken inside|chronic feelings of shame|feeling emotionally stuck|difficulty controlling anger|feeling lost due to trauma|problems with self[- ]image|negative self[- ]perception due to trauma|emotional instability|feeling like I\'m always on guard|feeling permanently damaged)\b'

# Comprehensive regex for schizophrenia self-identification
schizophrenia_regex = r'\b(schizophrenia|schizoaffective disorder|paranoid schizophrenia|schizophrenic|I have schizophrenia|diagnosed with schizophrenia|my schizophrenia|living with schizophrenia|schizo|schizo-type|schizophreniform|hallucinations|hearing voices|seeing things|delusions|paranoia|disorganized thinking|psychotic episode|psychosis|break from reality|feeling paranoid|auditory hallucinations|visual hallucinations|catatonic|paranoid thoughts|false beliefs|delusional thinking|paranoid delusions|thought disorder|feeling schizophrenic|acting schizo|I think I\'m schizo|people say I\'m schizophrenic|my schizo episodes|paranoid as hell|I feel like I\'m going crazy|I think I\'m losing touch with reality|I feel like I\'m hearing voices|clozapine|risperidone|seroquel|quetiapine|abilify|aripiprazole|haloperidol|antipsychotics|antipsychotic medication for schizophrenia|schizophrenia meds|schizo medication|been diagnosed with schizophrenia for years|living with schizophrenia|my schizophrenic diagnosis|I\'ve struggled with schizophrenia my whole life|I\'ve always known I have schizophrenia|my psychiatrist said I have schizophrenia|I\'m dealing with my schizophrenia|my mental health disorder is schizophrenia|mental illness|mental health issues|my mental health|mental health condition|struggling with mental health|unstable mentally|dealing with psychosis|mental breakdown|feeling disconnected from reality|talking about schizophrenia|schizophrenia symptoms|how to manage schizophrenia|schizophrenia treatment|understanding schizophrenia|schizo spectrum)\b'


posts = defaultdict(list)

with open('./offmychest_submissions.json', 'r', encoding='utf-8') as file:
    for line in file:
        data = json.loads(line)
        post = data['title'] + " " + data['selftext']
        if data and data['created_utc'] and data['author'] not in ("", "[deleted]", "[removed]") and data['selftext'] not in ("", "[deleted]", "[removed]") and re.search(schizophrenia_regex, post, re.IGNORECASE):
            posts['created_utc'].append(data['created_utc'])
            posts['id'].append(data['id'])
            posts['author'].append(data['author'])
            posts['titles'].append(data['title'])
            posts['contents'].append(data['selftext'])

print(len(posts['created_utc']))

# Create a DataFrame
df = pd.DataFrame({
    'Created_UTC': posts['created_utc'], 'Id': posts['id'], 'Author': posts['author'], 'Title': posts['titles'],
    'Content': posts['contents']
})

# Save DataFrame to a CSV file
save_to = 'offmychest_posts.csv'
df.to_csv(save_to, index=False)

print(f'{len(df)} posts saved to {save_to}')
